# Generated by Django 4.2.7 on 2023-11-10 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_taskwithtimestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskWithTimestamp',
        ),
    ]
