# Generated by Django 4.2.7 on 2023-11-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stopwatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('elapsed_time', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
