# Generated by Django 4.2.7 on 2023-11-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_remove_stopwatch_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopwatch',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
